services:
  user-service:
    build: .
    ports:
      - "8082:8080"
      - "50052:50051"
    environment:
      DB_HOST: postgres
      DB_PORT: "5434"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: users
      DB_SSLMODE: disable
      JWT_SECRET: some-secret
      TZ: Asia/Bangkok
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
      PGPORT: 5434
      TZ: Asia/Bangkok
    ports:
      - "5434:5434"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  pgweb:
    image: sosedoff/pgweb:latest
    ports:
      - "8083:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:postgres@postgres:5434/users?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
